### ISSUE TITLE
next-css 0.2.1-canary.4 incompatible with Next.js 9.0.7

### ISSUE THREAD

**Issue by samsisle** [zeit/next-plugins#543]
## Bug Report

I have been using the canary version of `zeit@/next-css` because version 1.0.1 does not minify my CSS chunk in production. 

After upgrading to Next.js 9.0.7, I receive this error when starting my application using the `now dev` command or using the script `'dev': 'next'` ->

<img width="1038" alt="Screen Shot 2019-09-30 at 12 47 38 PM" src="https://user-images.githubusercontent.com/28912696/65911119-f22f0e80-e380-11e9-8a93-9ae4b6661cc3.png">

I was able to reproduce my error on a blank slate Next.js application with the same dependencies: 
- @zeit/next-css: ^0.2.1-canary.4
- next: 9.0.7
- react: 16.10.1
- react-dom: 16.10.1
...
- now-cli: 16.3.0

Previous Next.js versions (9.0.6 and lower 9 versions) have been working flawlessly.

## System Information
- OS: MacOS Mojave Version 10.14.6
- Browser: Chrome 77.0.3865.90 (Official Build) (64-bit)

**Comment by brycejacobs** [comment]
Same issue after upgrading to 9.0.7.

**Comment by nghiepit** [comment]
Same issue https://spectrum.chat/next-js/general/next-9-0-7-and-zeit-next-sass-error~8a54bc3b-9a57-4e7d-8383-d162f2ced59f

**Comment by Timer** [comment]
Please try `next@v9.0.8-canary.3` -- this version should fix these broken plugins.

**Comment by cuonghv91** [comment]
@Timer it doesn't work on next@9.0.8-canary.3 neither, please check it again !

**Comment by kachkaev** [comment]
@cuonghv91 what is the error that you see in `next@9.0.8-canary.3`?

**Comment by cuonghv91** [comment]
It works perfect next@9.0.8-canary.3 guys !
Thanks @Timer

**Comment by samsisle** [comment]
Still getting the same errors with `next-css 0.2.1-canary.4`, for `next@9.0.8-canary.3 ` to `next@9.0.8-canary.5` and `next@9.0.8`.
